### ISSUE TITLE
xmpp client uses wrong transport

### ISSUE THREAD

**Issue by SergeyChehuta** [xmppjs/xmpp.js#551]
Hello, I am trying to run a test example with local xmpp server from ReactJS application.
There is my code:

```
const {Client} = require('@xmpp/client')
const client = new Client()
[...]
client.start('xmpp://localhost:5222')
.catch(err => { console.error('start failed', err) })
[...] 

```
and I get the error: No compatible connection method found.

I debugged start() function and discovered that it fails because in this code it expects wss://
instead of xmpp://

```
  connect(uri) {
    const Transport = this.transports.find(Transport => {
      try {
        return Transport.prototype.socketParameters(uri) !== undefined
      } catch (err) {
        return false
      }
    })

```
it calls 
```
  socketParameters(uri) {
    return uri.match(/^wss?:\/\//) ? uri : undefined
  }

```
and I have no idea why and how to get it working.
The same code works in the command line, like "node example.js" 
Could you advise, please?

**Comment by SergeyChehuta** [comment]
realized that in a browser it works using websockets

**Comment by parvindralogics** [comment]
Hi Sergey ,  Can you please explain little bit how you resolved it ? I am also running in same issue with 'xmpp:'  TLS connections .

**Comment by Christopher-Hayes** [comment]
For anyone coming across this issue (it's first page on google search). I had a lot of trouble finding any information, so putting this here if it helps:

**XMPP in browser**
You MUST use websockets, this error occurs when you try to use `xmpp://` when it is not supported. So, the protocol would have to be `ws://` instead of `xmpp://`. I haven't used websockets, so I can't get much more details.

**XMPP in electron**
You can use either `xmpp://` or `ws://`, but there's a bit of a gotcha here. Electron has a background process (background.js/.ts) and renderer process (main.js/.ts), you MUST run any `xmpp://` calls from the background process. When you try to run xmpp inside the main renderer process, it is exactly the same thing as trying to use xmpp in a browser/website and therefore it won't work unless you're using websockets. If you're using electron and getting that error, it means you're probably running xmpp in the wrong process. If you're unfamiliar with those processes, long story short you need to run the XMPP code in the background script, and use [ipcRenderer](https://www.electronjs.org/docs/api/ipc-renderer) and [ipcMain](https://www.electronjs.org/docs/api/ipc-main) to send events back and forth between the main script and the background script since they are two separate processes.

**Comment by sonnyp** [comment]
@Christopher-Hayes thanks for sharing

For reference, it is also possible to give the same `service` parameter to xmpp.js client in every environment and let it figure out the right endpoint.

But there are 2 requirements

1. The service must be a domain
2. DNS and/or Web Host Metadata are configured properly for the domain

See https://github.com/xmppjs/xmpp.js/tree/master/packages/client#client-1 and https://github.com/xmppjs/xmpp.js/blob/master/packages/resolve

**Comment by Christopher-Hayes** [comment]
@sonnyp oh, very interesting. Didn't know that was possible. Thanks for sharing.

Leaving this here for anyone looking for how to set that up: https://xmpp.org/extensions/xep-0156.html
