### ISSUE TITLE
Force Anonymous login on React Native?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [xmppjs/xmpp.js#770]
This might be related to #593 , I'm not sure, but when I use the lib on React Native, with username/password or not, the authentication method is always `PLAIN`:

Tracing down to `@xmpp/sasl/index.js` I saw this:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/7723097/63928757-560ca180-ca7a-11e9-8eb7-d5569d57b4e7.png">

But `features` only contains 4 mechanisms:

- PLAIN
- SCRAM-SHA-1
- CRAM-MD5
- DIGEST-MD5

And no `ANONYMOUS`

I need anonymous authentication for account registration first, then login using registered account. From above info, I created a client:

```jsx
    this.xmpp = client({
      service: 'ws://testdomain:7071/ws',
      domain: 'testdomain',
      credentials: function authenticate (auth, mechanism) {
        console.log('authenticate', mechanism)
        const cred = null
        return auth(cred)
      }
    })
```

and as expected, `mechanism` is always `PLAIN`

Is there a way to fix this?

**Comment by sonnyp** [comment]
The issue seems to be that your server does not offer anonymous authentication on that domain.

You probably should use https://xmpp.org/extensions/xep-0077.html directly instead. Unfortunally xmpp.js does not have helpers for it but it should be quite easy to implement yourself and if you'd like to contribute the code to xmpp.js I'd be happy to help.

I could be wrong but I'm not aware of registration from an anonymous session being a thing in XMPP anyway.

**Comment by sonnyp** [comment]
see https://github.com/xmppjs/xmpp.js/issues/783
